apiVersion: 1

datasources:
  - name: InfluxDB_home
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: $INFLUX_TOKEN
    jsonData:
      version: Flux
      organization: home
      defaultBucket: $INFLUX_BUCKET
      tlsSkipVerify: true